### ISSUE TITLE
node-red crashes when trying to announce transaction to NEM

### ISSUE THREAD

**Issue by gigonzalezs** [nemtech/nem2-prototyping-tool#10]
If peer-nodes are down but api-rest is ok (shutdown problem), a node-red flow with NEM announcement node crashes the node-red server, because NEM API returns HTTP 503 / 404

Network Trace  from node-red to NEM API:

PUT /transaction HTTP/1.1
Host: localhost:3000

{"payload":"C900000... 724,"networkType":144}

HTTP/1.1 503 Service Unavailable

{"code":"ServiceUnavailable","message":"connection failed"}

====================================
node-red stack trace:

26 Sep 00:07:58 - [red] Uncaught Exception:
26 Sep 00:07:58 - Error: Service Unavailable
    at Request.callback (/usr/local/lib/node_modules/node-red-contrib-nem2/node_modules/superagent/lib/node/index.js:675:11)
    at /usr/local/lib/node_modules/node-red-contrib-nem2/node_modules/superagent/lib/node/index.js:883:18
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-red-contrib-nem2/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
MacBook-Pro-de-Iuni-134:generated-addresses gilbert$ node-red
26 Sep 00:13:59 - [info]

**Comment by jorisadri** [comment]
This is a [bug](https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/22) in the SDK. 
If you check [this repository](https://github.com/jorisadri/nem2-prototyping-tool) you will see that an update is coming do address this issues.

**Comment by dgarcia360** [comment]
Closed, should be solved with the latest update.
